steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-east1-docker.pkg.dev/nestjs-microservices-430210/image-registry/authentication-ms",
        "-f",
        "dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-east1-docker.pkg.dev/nestjs-microservices-430210/image-registry/authentication-ms",
      ]
options: logging: CLOUD_LOGGING_ONLY  
